line-length = 88
target-version = "py310"

[format]
line-ending = "lf"

[lint]
ignore = [
  "E501", "E701", "E702", "ASYNC240", "RUF100", "E902", "T201",
  "E402", # module-import-not-at-top-of-file
  "UP037", # quoted-annotation
  "RUF001", # ambiguous-unicode-character-string
  "RUF002", # ambiguous-unicode-character-docstring
  "RUF003", # ambiguous-unicode-character-comment
  "TID252", # relative-imports
]
select = [
  "F", # Pyflakes
  "W", # pycodestyle warnings
  "E", # pycodestyle errors
  "I", # isort
  "UP", # pyupgrade
  "ASYNC", # flake8-async
  "C4", # flake8-comprehensions
  "T10", # flake8-debugger
  "T20", # flake8-print
  "PYI", # flake8-pyi
  "PT", # flake8-pytest-style
  "Q", # flake8-quotes
  "TID", # flake8-tidy-imports
  "RUF", # Ruff-specific rules
]

[lint.isort]
extra-standard-library = ["typing_extensions"]
force-sort-within-sections = true

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.per-file-ignores]
"src/nonebot_plugin_parser_lite/utils/_standalone_fake.py" = ["ALL"]
"src/nonebot_plugin_parser_lite/utils/env.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/_flags.py" = ["I001"]
"src/nonebot/__init__.py" = ["I001"]
"src/nonebot_plugin_localstore/__init__.py" = ["I001"]
"src/nonebot/adapters/__init__.py" = ["I001"]
"src/nonebot/log/__init__.py" = ["I001"]
"src/nonebot/matcher/__init__.py" = ["I001"]
"src/nonebot/params/__init__.py" = ["I001"]
"src/nonebot/permission/__init__.py" = ["I001"]
"src/nonebot/rule/__init__.py" = ["I001"]
"src/nonebot/typing/__init__.py" = ["I001"]
"src/nonebot_plugin_alconna/__init__.py" = ["I001"]
"src/nonebot_plugin_alconna/extension/__init__.py" = ["I001"]
"src/nonebot_plugin_alconna/uniseg/__init__.py" = ["I001"]
"src/nonebot_plugin_htmlrender/__init__.py" = ["I001"]
"src/nonebot_plugin_uninfo/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/creator.py" = ["I001"]
"src/nonebot_plugin_parser_lite/data.py" = ["I001"]
"src/nonebot_plugin_parser_lite/exception.py" = ["I001"]
"src/nonebot_plugin_parser_lite/config.py" = ["I001"]
"src/nonebot_plugin_parser_lite/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/helper.py" = ["I001"]
"src/nonebot_plugin_parser_lite/constants.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/common.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/browser.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/ffmpeg.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/cookie.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/cache.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/format.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/a2v.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/opus.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/favorite_list.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/live.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/article.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/login.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/sign.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/dynamic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/client.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/exceptions.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/video.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/credential.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/bangumi.py" = ["I001"]
"src/nonebot_plugin_parser_lite/utils/bilibili/user.py" = ["I001"]
"src/nonebot_plugin_parser_lite/download/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/download/task.py" = ["I001"]
"src/nonebot_plugin_parser_lite/download/client.py" = ["I001"]
"src/nonebot_plugin_parser_lite/matchers/rule.py" = ["I001"]
"src/nonebot_plugin_parser_lite/matchers/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/matchers/filter.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/kugou.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/netease.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/kuwo.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/base.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/coolapk/reply.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/coolapk/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/coolapk/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/coolapk/feed.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/show_comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/article.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/auth.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/longText.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/statuses_comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/statuses.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/show.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/weibo/article_comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/rednote/discovery.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/rednote/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/drawingDetail.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/commentList.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/encrypt.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/models.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/illu/articleByIdV2.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/acfun/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/acfun/video.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/linuxdo/topic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/linuxdo/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/linuxdo/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douban/share.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douban/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douban/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douban/comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douban/post.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/heybox/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/heybox/sm.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/heybox/encrypt.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/heybox/model.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/topic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/share.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/comments.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/gallery.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/video.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/buff/news.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douyin/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douyin/note.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douyin/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/douyin/video_or_article.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/hupu/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/hupu/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/hupu/bbs.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/hupu/comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/duitang/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/duitang/model.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/tieba/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/tieba/models.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/tieba/utils.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/article.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/sign.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/answer.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/question.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zhihu/root_comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/wmpvp/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/wmpvp/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/wmpvp/comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/wmpvp/post.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/wmpvp/news.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/x/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/x/model.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/lofter/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/lofter/comments.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/lofter/post.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/doubao/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/doubao/model.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/qsmusic/share.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/qsmusic/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/fiveeplay/topic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/fiveeplay/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/miyoushe/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/miyoushe/comment.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/miyoushe/structed_content.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/miyoushe/sticker.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/miyoushe/post.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zlb/topic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zlb/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/zlb/util.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/opus.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/common.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/live.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/favlist.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/dynamic.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/video.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/bilibili/bangumi.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/kuaishou/state.py" = ["I001"]
"src/nonebot_plugin_parser_lite/parsers/kuaishou/__init__.py" = ["I001"]
"src/nonebot_plugin_parser_lite/render/__init__.py" = ["I001"]
