# Auto-generated by standalone workflow. Do not edit.
Depends = None  # type: ignore
Event = None  # type: ignore
Matcher = None  # type: ignore
PluginMetadata = None  # type: ignore
Rule = None  # type: ignore
SUPERUSER = None  # type: ignore
T_State = None  # type: ignore
current_bot = None  # type: ignore
current_event = None  # type: ignore
get_driver = None  # type: ignore
get_plugin_config = None  # type: ignore
inherit_supported_adapters = None  # type: ignore
logger = None  # type: ignore
on_command = None  # type: ignore
require = None  # type: ignore
to_me = None  # type: ignore
