#!/usr/bin/env python3
"""
Upstream auto-patcher: dynamically inject standalone support.
Phase 1: scan → Phase 2: generate stubs → Phase 3-5: patch files.
"""
import ast
import os
import re
import sys
from pathlib import Path

SRC = Path(os.environ.get("PATCHER_SRC", "src/nonebot_plugin_parser_lite"))

# ═══════════════════════════════════════════════════════════════
# Phase 1: scan ALL .py files, categorize NoneBot imports by origin
# ═══════════════════════════════════════════════════════════════
IMPORT_RE = re.compile(
    r"^from\s+(nonebot\.[a-z_]+?)\s+import\s+(.+)$|^from\s+(nonebot)\s+import\s+(.+)$",
    re.MULTILINE,
)
TYPES_FROM: dict[str, set[str]] = {}  # module -> symbols
SOURCE_FILES: list[str] = []

for py_file in sorted(SRC.rglob("*.py")):
    if py_file.name in ("_flags.py", "env.py", "_standalone_fake.py"):
        continue
    text = py_file.read_text(encoding="utf-8")
    matched = False
    for m in IMPORT_RE.finditer(text):
        module = m.group(1) or m.group(3)  # nonebot.xxx or nonebot
        names_str = m.group(2) or m.group(4)  # comma-separated
        if names_str:
            for n in re.split(r",\s*", names_str.split("#")[0]):
                n = n.strip().split(" as ")[0]
                if n and not n.startswith("("):
                    TYPES_FROM.setdefault(module, set()).add(n)
                    matched = True
    if matched:
        SOURCE_FILES.append(str(py_file.relative_to(SRC)))

print(f"[patches] {len(SOURCE_FILES)} files with NoneBot imports across {len(TYPES_FROM)} modules")
for mod, syms in sorted(TYPES_FROM.items()):
    print(f"  {mod}: {sorted(syms)}")

# ═══════════════════════════════════════════════════════════════
# Phase 2: generate _standalone_fake.py — stub for everything
# ═══════════════════════════════════════════════════════════════
all_stubs = []
for mod, syms in sorted(TYPES_FROM.items()):
    for s in sorted(syms):
        all_stubs.append(f"{s} = None  # type: ignore")

STUB_FILE = SRC / "utils" / "_standalone_fake.py"
STUB_FILE.write_text(
    "# Auto-generated by sync-upstream action. Do not edit.\n"
    + "\n".join(all_stubs) + "\n",
    encoding="utf-8",
)
print(f"[patches] Generated {STUB_FILE} ({len(all_stubs)} stubs)")

# ═══════════════════════════════════════════════════════════════
# Phase 3: patch __init__.py — wrap in if _STANDALONE: else:
# ═══════════════════════════════════════════════════════════════
init = SRC / "__init__.py"
init_text = init.read_text(encoding="utf-8")

guard = (
    'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n'
    '\n'
    'if _STANDALONE:\n'
    '    from .utils._standalone_fake import *  # noqa: F403\n'
    '    from logging import getLogger as _getLogger\n'
    '    logger = _getLogger("parser-lite")\n'
    '    try:\n'
    '        from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
    '        scheduler = AsyncIOScheduler()\n'
    '        scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
    '        try: scheduler.start()\n'
    '        except RuntimeError: pass\n'
    '    except ImportError:\n'
    '        scheduler = None  # type: ignore\n'
    '    def clear_result_cache() -> None: pass\n'
    'else:\n'
)
# If init already has _flags import, just skip (already patched or alone branch)
if "_STANDALONE" in init_text:
    print("[patches] __init__.py: already has _STANDALONE guard, skipping")
else:
    indented = "\n".join(
        "    " + line if line.strip() else ""
        for line in init_text.split("\n")
    )
    init.write_text(guard + indented, encoding="utf-8")
    print(f"[patches] Patched {init}")

# ═══════════════════════════════════════════════════════════════
# Phase 4: patch config.py — standalone path init
# ═══════════════════════════════════════════════════════════════
cfg = SRC / "config.py"
cfg_text = cfg.read_text(encoding="utf-8")

if "IS_STANDALONE" not in cfg_text:
    standalone = """

# ── Standalone (AstrBot) path initialization ──────────────────
if IS_STANDALONE:
    import os as _standalone_os
    from pathlib import Path as PathSync

    base_dir = Path(_standalone_os.environ.get("PARSER_LITE_BASE_DIR", str(PathSync().cwd())))
    _cache_dir: Path = Path(base_dir / "cache")
    _config_dir: Path = Path(base_dir / "config")
    _data_dir: Path = Path(base_dir / "data")
    for d in [_cache_dir, _config_dir, _data_dir]:
        PathSync(d).mkdir(parents=True, exist_ok=True)
"""
    cfg_text = cfg_text.replace(
        "from .constants import PlatformEnum",
        "from .constants import PlatformEnum\nfrom .utils.env import IS_STANDALONE",
    )
    cfg_text += standalone
    cfg.write_text(cfg_text, encoding="utf-8")
    print(f"[patches] Patched {cfg}")

print("[patches] Done")
