"""
Upstream auto-patcher: dynamically inject standalone support into
nonebot-plugin-parser-lite sourcedirectory.
Runs in GitHub Actions to keep our fork compatible with upstream/main.
"""
import ast
import os
import re
import sys
from pathlib import Path

SRC = Path(os.environ.get("PATCHER_SRC", "src/nonebot_plugin_parser_lite"))

# ── Phase 1: scan all .py files for NoneBot imports ──
FAKE_TYPES: set[str] = set()
NEEDS_STANDALONE_GUARD: list[Path] = []
NB_IMPORT_RE = re.compile(
    r"^from nonebot(\.[a-z_]+)? import\s+(.+)$|^import nonebot(\.[a-z_]+)?",
    re.MULTILINE,
)

for py_file in sorted(SRC.rglob("*.py")):
    text = py_file.read_text(encoding="utf-8")
    found = False
    for m in NB_IMPORT_RE.finditer(text):
        found = True
        names = m.group(2)
        if names:
            for n in re.split(r",\s*", names.split("#")[0].split(" as ")[0]):
                n = n.strip()
                if n and not n.startswith("("):
                    FAKE_TYPES.add(n)
    if found and not any(
        py_file.relative_to(SRC).as_posix().endswith(x)
        for x in ("utils/_flags.py", "utils/env.py")
    ):
        NEEDS_STANDALONE_GUARD.append(py_file.relative_to(SRC))

print(f"[patches] Found {len(NEEDS_STANDALONE_GUARD)} files with NoneBot imports")
print(f"[patches] NoneBot symbols to fake: {sorted(FAKE_TYPES)}")

# ── Phase 2: generate fake module ──
_stubs = []
for t in sorted(FAKE_TYPES):
    _stubs.append(f"    {t} = None  # type: ignore")

STUB_FILE = SRC / "utils" / "_standalone_fake.py"
STUB_FILE.write_text(
    "# Auto-generated by sync-upstream action. Do not edit.\n"
    "# Provides fake NoneBot symbols for standalone (AstrBot) environment.\n"
    "_FAKE_SYMBOLS = {"
    + ", ".join(sorted(FAKE_TYPES))
    + "}\n"
    + "\n".join(_stubs) + "\n",
    encoding="utf-8",
)
print(f"[patches] Generated {STUB_FILE} ({len(_stubs)} stubs)")

# ── Phase 3: patch __init__.py ──
init = SRC / "__init__.py"
init_text = init.read_text(encoding="utf-8")

# Add standalone guard: wrap everything after _flags import in if/else
if "from .utils._flags import" in init_text:
    lines = init_text.split("\n")
    new_lines = []
    in_standalone = False
    for line in lines:
        stripped = line.strip()
        # Insert standalone guard after _flags import
        if stripped.startswith("from .utils._flags import"):
            new_lines.append(line)
            new_lines.append("")
            new_lines.append("if _STANDALONE:")
            new_lines.append("    from .utils._standalone_fake import *  # noqa: F403")
            new_lines.append("else:")
            in_standalone = True
            continue
        if in_standalone and stripped and not stripped.startswith("from .utils"):
            # Indent everything for the standalone branch
            new_lines.append("    " + line if line.strip() else line)
            continue
        if in_standalone and not stripped:
            new_lines.append(line)
            continue
        new_lines.append(line)
    init.write_text("\n".join(new_lines), encoding="utf-8")
    print(f"[patches] Patched {init}")
else:
    # Fallback: no _flags import, add at top
    guard = (
        'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n'
        '\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        '    from logging import getLogger as _getLogger\n'
        '    logger = _getLogger("parser-lite")\n'
        '    PluginMetadata = None  # type: ignore\n'
        '    inherit_supported_adapters = None  # type: ignore\n'
        '    from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
        '    scheduler = AsyncIOScheduler()\n'
        '    scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
        '    try: scheduler.start()\n'
        '    except RuntimeError: pass\n'
        '    def clear_result_cache() -> None: pass\n'
        'else:\n'
    )
    init.write_text(guard + "\n".join(lines), encoding="utf-8")
    print(f"[patches] Patched {init} (no existing _flags import)")

# ── Phase 4: patch config.py ──
cfg = SRC / "config.py"
cfg_text = cfg.read_text(encoding="utf-8")

if "IS_STANDALONE" not in cfg_text:
    # Inject standalone config initialization at the bottom
    standalone_block = """

# ── Standalone (AstrBot) path initialization ──────────────────
if IS_STANDALONE:
    from pathlib import Path as PathSync

    base_dir = Path(os.environ.get("PARSER_LITE_BASE_DIR", PathSync().cwd()))
    _cache_dir: Path = Path(base_dir / "cache")
    _config_dir: Path = Path(base_dir / "config")
    _data_dir: Path = Path(base_dir / "data")
    for d in [_cache_dir, _config_dir, _data_dir]:
        PathSync(d).mkdir(parents=True, exist_ok=True)
    pconfig: Config = Config()

    class GlobalConfig(BaseModel):
        log_level: str | int = "INFO"
        nickname: list[str] = ["parser-lite"]

    gconfig = GlobalConfig()
"""
    # Patch imports at top to add IS_STANDALONE
    if "from .utils.env import IS_STANDALONE" not in cfg_text:
        cfg_text = cfg_text.replace(
            "from .constants import PlatformEnum",
            "from .constants import PlatformEnum\nfrom .utils.env import IS_STANDALONE",
        )
    # Wrap existing init code in if/else
    cfg_text = cfg_text.replace(
        "_driver = get_driver()",
        "if IS_STANDALONE:\n    _driver = None\nelse:\n    _driver = get_driver()",
    )
    cfg_text = cfg_text.replace(
        "pconfig: Config = get_plugin_config(Config)",
        "pconfig: Config = get_plugin_config(Config) if not IS_STANDALONE else Config()",
    )
    # Append standalone block
    cfg_text += standalone_block
    cfg.write_text(cfg_text, encoding="utf-8")
    print(f"[patches] Patched {cfg}")
else:
    print(f"[patches] {cfg} already patched, skipping")

# ── Phase 5: patch helper.py ──
helper = SRC / "helper.py"
helper_text = helper.read_text(encoding="utf-8")

if "from .utils._standalone_fake import" not in helper_text:
    guard = (
        'from .utils._flags import _STANDALONE\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        'else:\n'
    )
    # Insert after imports
    helper_text = helper_text.replace(
        "\n\n",
        f"\n{guard}",
        1,
    )
    helper.write_text(helper_text, encoding="utf-8")
    print(f"[patches] Patched {helper}")

print("[patches] Done")
