#!/usr/bin/env python3
"""Generate standalone files — called by standalone.yml workflow."""
import os
import re

SRC = "src/nonebot_plugin_parser_lite"
os.makedirs(f"{SRC}/utils", exist_ok=True)

# env.py
with open(f"{SRC}/utils/env.py", "w") as f:
    f.write('import os\n\nIS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE") == "1"\n')
print("  env.py")

# _flags.py
with open(f"{SRC}/utils/_flags.py", "w") as f:
    f.write("""import os

_IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE", "") == "1"
PARSER_LITE_STANDALONE = _IS_STANDALONE
PARSER_LITE_PRE = "plite_"
if _IS_STANDALONE:
    _STANDALONE = True
    def _get_flag(flag: str) -> str:
        return os.environ.get(f"{PARSER_LITE_PRE}{flag}", "")
else:
    from nonebot import get_driver
    _STANDALONE = False
    def _get_flag(flag: str) -> str:
        return getattr(get_driver().config, f"{PARSER_LITE_PRE}{flag}", "")
""")
print("  _flags.py")

# _standalone_fake.py
stubs, seen = [], set()
for root, dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith(".py") or fn in ("_flags.py", "env.py", "_standalone_fake.py"):
            continue
        in_paren = False
        for line in open(os.path.join(root, fn), encoding="utf-8").read().split("\n"):
            m = re.match(r"from\s+(nonebot(\.[a-z_]+)?)\s+import\s+(.+?)(?:\s*#.*)?$", line)
            if m:
                raw = m.group(3).strip()
                if raw.endswith("("):
                    in_paren = True
                    raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n)
                        stubs.append(n)
            elif in_paren:
                raw = line.split("#")[0].strip()
                if raw.endswith(")"):
                    in_paren = False
                    raw = raw[:-1]
                if raw.endswith(","):
                    raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n)
                        stubs.append(n)
with open(f"{SRC}/utils/_standalone_fake.py", "w") as f:
    f.write("# Auto-generated by standalone workflow. Do not edit.\n")
    for s in sorted(stubs):
        f.write(f"{s} = None  # type: ignore\n")
print(f"  _standalone_fake.py ({len(stubs)} stubs)")

# __init__.py
init_path = f"{SRC}/__init__.py"
text = open(init_path, encoding="utf-8").read()
if "_STANDALONE" in text:
    print("  __init__.py already patched")
else:
    guard = (
        'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n'
        '\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        '    from logging import getLogger as _getLogger\n'
        '    logger = _getLogger("parser-lite")\n'
        '    try:\n'
        '        from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
        '        scheduler = AsyncIOScheduler()\n'
        '        scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
        '        try: scheduler.start()\n'
        '        except RuntimeError: pass\n'
        '    except ImportError:\n'
        '        scheduler = None\n'
        '    def clear_result_cache() -> None: pass\n'
        'else:\n'
    )
    indented = "\n".join("    " + line if line.strip() else "" for line in text.split("\n"))
    open(init_path, "w", encoding="utf-8").write(guard + indented)
    print("  __init__.py patched")

# ruff.toml — inject bridge-compatible ignores + per-file-ignores
rt_path = "ruff.toml"
if os.path.exists(rt_path):
    lines = open(rt_path, encoding="utf-8").read().split("\n")
    if "Auto-generated by standalone" not in "\n".join(lines):
        with open(rt_path, "r", encoding="utf-8") as f:
            full = f.read()
        # Add bridge ignores to upstream's ignore list
        full = full.replace(
            'ignore = [',
            'ignore = [\n  "E501", "E701", "E702", "ASYNC240", "RUF100", "E902", "T201",'
        )
        full += '\n# Auto-generated by standalone workflow\n'
        full += '[lint.per-file-ignores]\n'
        full += '"src/nonebot_plugin_parser_lite/__init__.py" = ["I001", "Q000", "F405"]\n'
        full += '"src/nonebot_plugin_parser_lite/utils/_flags.py" = ["E731"]\n'
        full += '"src/nonebot_plugin_parser_lite/utils/env.py" = ["I001"]\n'
        full += '"src/nonebot_plugin_parser_lite/utils/_standalone_fake.py" = ["ALL"]\n'
        with open(rt_path, "w", encoding="utf-8") as f:
            f.write(full)
        print("  ruff.toml injected")
