#!/usr/bin/env python3
"""
Generate standalone files — called by standalone.yml workflow.
Zero-hardcode design: tracks generated files for auto ruff exclusion.
"""
import os
import re

SRC = os.environ.get("PATCHER_SRC", "src/nonebot_plugin_parser_lite")
SRC_PREFIX = SRC
os.makedirs(f"{SRC}/utils", exist_ok=True)
GENERATED_FILES: list[str] = []


def _write(path: str, content: str):
    full = os.path.join(SRC, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    GENERATED_FILES.append(f"{SRC_PREFIX}/{path}")
    print(f"  {path}")

# ── env.py ──
_write("utils/env.py",
    'import os\n\n'
    'IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE") == "1"\n')

# ── _flags.py ──
_write("utils/_flags.py",
    'import os\n\n'
    '_IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE", "") == "1"\n'
    'PARSER_LITE_STANDALONE = _IS_STANDALONE\n'
    'PARSER_LITE_PRE = "plite_"\n'
    'if _IS_STANDALONE:\n'
    '    _STANDALONE = True\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return os.environ.get(f"{PARSER_LITE_PRE}{flag}", "")\n'
    'else:\n'
    '    from nonebot import get_driver\n'
    '\n'
    '    _STANDALONE = False\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return getattr(get_driver().config, f"{PARSER_LITE_PRE}{flag}", "")\n')

# ── _standalone_fake.py ──
stubs, seen = [], set()
submods: set[str] = set()  # e.g. {"nonebot.log", "nonebot.adapters"}
for root, dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith(".py") or fn in ("_flags.py", "env.py", "_standalone_fake.py"):
            continue
        in_paren = False
        with open(os.path.join(root, fn), encoding="utf-8") as _f:
            _text = _f.read()
        for line in _text.split("\n"):
            m = re.match(r"from\s+(nonebot(\.[a-z_]+)?)\s+import\s+(.+?)(?:\s*#.*)?$", line)
            if m:
                path = m.group(1)  # e.g. "nonebot.log" or "nonebot"
                if "." in path:
                    submods.add(path)
                raw = m.group(3).strip()
                if raw.endswith("("): in_paren = True; raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)
            elif in_paren:
                raw = line.split("#")[0].strip()
                if raw.endswith(")"): in_paren = False; raw = raw[:-1]
                if raw.endswith(","): raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)

stub_content = "# Auto-generated by standalone workflow. Do not edit.\n"
stub_content += "\n".join(f"{s} = None  # type: ignore" for s in sorted(stubs)) + "\n"
_write("utils/_standalone_fake.py", stub_content)
print(f"  ({len(stubs)} stubs: {', '.join(sorted(stubs))})")

# ── nonebot stub package ──
# Upstream files do `from nonebot import ...` which fails if nonebot is not installed.
# This stub package provides recursive mocks so all imports and calls succeed silently.
_SRC_DIR = os.path.dirname(SRC)  # src/
_nb_dir = os.path.join(_SRC_DIR, "nonebot")
os.makedirs(_nb_dir, exist_ok=True)
_nb_init = os.path.join(_nb_dir, "__init__.py")
if not os.path.exists(_nb_init):
    _nb_stub = '''# Auto-generated standalone stub for nonebot
class _NonebotMock:
    """Recursive mock: attribute → self, call → self, iter → [self], falsy."""
    def __getattr__(self, name):
        return self
    def __call__(self, *args, **kwargs):
        return self
    def __iter__(self):
        return iter([self])
    def __bool__(self):
        return False
    def __repr__(self):
        return "nonebot-mock"
    def __contains__(self, item):
        return True

_m = _NonebotMock()
'''
    for s in sorted(stubs):
        _nb_stub += f'{s} = _m\n'
    _nb_stub += '''
import logging
logger = logging.getLogger("parser-lite")
'''
    # Submodule fallback: `from nonebot.adapters import X` calls __getattr__ on module
    _nb_stub += '''
import sys as _sys

def __getattr__(name):
    sub = _NonebotMock()
    setattr(_sys.modules[__name__], name, sub)
    return sub
'''
    with open(_nb_init, "w", encoding="utf-8") as f:
        f.write(_nb_stub)
    GENERATED_FILES.append("src/nonebot/__init__.py")
    print(f"  nonebot/__init__.py ({len(stubs)} stubs)")

# ── nonebot_plugin_localstore stub ──
_nls_dir = os.path.join(_SRC_DIR, "nonebot_plugin_localstore")
os.makedirs(_nls_dir, exist_ok=True)
_nls_init = os.path.join(_nls_dir, "__init__.py")
if not os.path.exists(_nls_init):
    _nls_stub = '''# Auto-generated standalone stub for nonebot_plugin_localstore
from pathlib import Path as _Path

_base = _Path("data")
def get_plugin_cache_dir():
    return _base / "cache"
def get_plugin_config_dir():
    return _base / "config"
def get_plugin_data_dir():
    return _base / "data"
'''
    with open(_nls_init, "w", encoding="utf-8") as f:
        f.write(_nls_stub)
    GENERATED_FILES.append("src/nonebot_plugin_localstore/__init__.py")
    print("  nonebot_plugin_localstore/__init__.py")

# ── nonebot submodule stubs ──
# `from nonebot.log import logger` requires actual nonebot/log/__init__.py stub,
# not just __getattr__ on the parent module.
for _sm in sorted(submods):
    _parts = _sm.split(".")
    _sm_dir = os.path.join(_SRC_DIR, *_parts)
    os.makedirs(_sm_dir, exist_ok=True)
    _sm_init = os.path.join(_sm_dir, "__init__.py")
    if not os.path.exists(_sm_init):
        _sm_stub = f'''# Auto-generated standalone stub for {_sm}
class _NonebotMock:
    def __getattr__(self, name):
        return self
    def __call__(self, *args, **kwargs):
        return self
    def __iter__(self):
        return iter([self])
    def __bool__(self):
        return False
    def __repr__(self):
        return "nonebot-mock"
    def __contains__(self, item):
        return True

_m = _NonebotMock()
'''
        for s in sorted(stubs):
            _sm_stub += f'{s} = _m\n'
        _sm_stub += '''
import logging
logger = logging.getLogger("parser-lite")
'''
        with open(_sm_init, "w", encoding="utf-8") as f:
            f.write(_sm_stub)
        GENERATED_FILES.append("src/" + "/".join(_parts) + "/__init__.py")
        print(f"  {'/'.join(_parts)}/__init__.py")

# ── __init__.py ──
init_path = f"{SRC}/__init__.py"
text = open(init_path, encoding="utf-8").read()
if "_STANDALONE" in text:
    print("  __init__.py already patched, skipping")
else:
    guard = (
        'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        '    from logging import getLogger as _getLogger\n'
        '    logger = _getLogger("parser-lite")\n'
        '    try:\n'
        '        from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
        '        scheduler = AsyncIOScheduler()\n'
        '        scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
        '        try: scheduler.start()\n'
        '        except RuntimeError: pass\n'
        '    except ImportError:\n'
        '        scheduler = None\n'
        '    def clear_result_cache() -> None: pass\n'
        'else:\n'
    )
    indented = "\n".join("    " + line if line.strip() else "" for line in text.split("\n"))
    with open(init_path, "w", encoding="utf-8") as f:
        f.write(guard + indented)
    GENERATED_FILES.append(f"{SRC_PREFIX}/__init__.py")
    print("  __init__.py patched")

# ── ruff.toml ──
rt_path = "ruff.toml"
BRIDGE_IGNORES = ["E501", "E701", "E702", "ASYNC240", "RUF100", "E902", "T201"]
if os.path.exists(rt_path):
    with open(rt_path, encoding="utf-8") as f:
        full = f.read()
    if '  "E501"' not in full:
        full = full.replace(
            "ignore = [",
            "ignore = [\n  " + ", ".join(f'"{r}"' for r in BRIDGE_IGNORES) + ","
        )
    # Remove old per-file-ignores (if any), regenerate from scratch
    lines = full.split("\n")
    clean = []
    skip = False
    for line in lines:
        if line.startswith("[lint.per-file-ignores]"):
            skip = True
            continue
        if skip and line.startswith("["):
            skip = False
        if not skip:
            clean.append(line)
    full = "\n".join(clean).rstrip("\n") + "\n\n[lint.per-file-ignores]\n"
    full += f'"{SRC_PREFIX}/utils/_standalone_fake.py" = ["ALL"]\n'
    for gf in GENERATED_FILES:
        if gf != f"{SRC_PREFIX}/utils/_standalone_fake.py":
            full += f'"{gf}" = ["I001"]\n'
    # Scan all upstream Python files and add I001 ignores (they often have
    # unsorted imports due to conditional nonebot imports at module level)
    for root, dirs, files in os.walk(SRC):
        for fn in files:
            if not fn.endswith(".py"):
                continue
            rel = os.path.relpath(os.path.join(root, fn)).replace("\\", "/")
            if any(rel.startswith(gf.replace("\\", "/")) for gf in GENERATED_FILES):
                continue
            full += f'"{rel}" = ["I001"]\n'
    with open(rt_path, "w", encoding="utf-8") as f:
        f.write(full)
    print(f"  ruff.toml injected ({len(GENERATED_FILES)} files)")

# ── Strip NoneBot deps + remove version upper bounds ──
req_path = "requirements.txt"
if os.path.exists(req_path):
    with open(req_path, encoding="utf-8") as f:
        req_lines = f.readlines()
    clean = []
    for ln in req_lines:
        stripped = ln.strip()
        if not stripped or stripped.startswith("#"):
            clean.append(ln)
            continue
        if "nonebot" in stripped.lower():
            continue
        # Remove version upper bound (keep only lower bound)
        pkg_name = re.split(r"[<>=!~]", stripped)[0].strip()
        lower = re.search(r"(>=?[^,;\s]+)", stripped)
        if lower:
            clean.append(f"{pkg_name}{lower.group(1)}\n")
        else:
            clean.append(f"{pkg_name}\n")
    if len(clean) != len(req_lines):
        with open(req_path, "w", encoding="utf-8") as f:
            f.writelines(clean)
        print(f"  requirements.txt: stripped {len(req_lines) - len(clean)} entries")
