#!/usr/bin/env python3
"""
Generate standalone files — called by standalone.yml workflow.
Zero-hardcode design: tracks generated files for auto ruff exclusion.
"""
import os
import re

SRC = os.environ.get("PATCHER_SRC", "src/nonebot_plugin_parser_lite")
SRC_PREFIX = SRC  # e.g. "src/nonebot_plugin_parser_lite"
os.makedirs(f"{SRC}/utils", exist_ok=True)
GENERATED_FILES: list[str] = []


def _write(path: str, content: str):
    full = os.path.join(SRC, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    GENERATED_FILES.append(f"{SRC_PREFIX}/{path}")
    print(f"  {path}")

# ── env.py ──
_write("utils/env.py",
    'import os\n\n'
    'IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE") == "1"\n')

# ── _flags.py ──
_write("utils/_flags.py",
    'import os\n\n'
    '_IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE", "") == "1"\n'
    'PARSER_LITE_STANDALONE = _IS_STANDALONE\n'
    'PARSER_LITE_PRE = "plite_"\n'
    'if _IS_STANDALONE:\n'
    '    _STANDALONE = True\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return os.environ.get(f"{PARSER_LITE_PRE}{flag}", "")\n'
    'else:\n'
    '    from nonebot import get_driver\n'
    '\n'
    '    _STANDALONE = False\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return getattr(get_driver().config, f"{PARSER_LITE_PRE}{flag}", "")\n')

# ── _standalone_fake.py — scan ALL source files for NoneBot imports ──
stubs, seen = [], set()
for root, dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith(".py") or fn in ("_flags.py", "env.py", "_standalone_fake.py"):
            continue
        in_paren = False
        with open(os.path.join(root, fn), encoding="utf-8") as _f:
            _text = _f.read()
        for line in _text.split("\n"):
            m = re.match(r"from\s+(nonebot(\.[a-z_]+)?)\s+import\s+(.+?)(?:\s*#.*)?$", line)
            if m:
                raw = m.group(3).strip()
                if raw.endswith("("):
                    in_paren = True
                    raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)
            elif in_paren:
                raw = line.split("#")[0].strip()
                if raw.endswith(")"): in_paren = False; raw = raw[:-1]
                if raw.endswith(","): raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)

stub_content = "# Auto-generated by standalone workflow. Do not edit.\n"
stub_content += "\n".join(f"{s} = None  # type: ignore" for s in sorted(stubs)) + "\n"
_write("utils/_standalone_fake.py", stub_content)
print(f"  ({len(stubs)} stubs: {', '.join(sorted(stubs))})")

# ── __init__.py — inject if _STANDALONE: guard ──
init_path = f"{SRC}/__init__.py"
text = open(init_path, encoding="utf-8").read()
if "_STANDALONE" in text:
    print("  __init__.py already patched, skipping")
else:
    guard = (
        'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n'
        '\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        '    from logging import getLogger as _getLogger\n'
        '    logger = _getLogger("parser-lite")\n'
        '    try:\n'
        '        from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
        '        scheduler = AsyncIOScheduler()\n'
        '        scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
        '        try: scheduler.start()\n'
        '        except RuntimeError: pass\n'
        '    except ImportError:\n'
        '        scheduler = None\n'
        '    def clear_result_cache() -> None: pass\n'
        'else:\n'
    )
    indented = "\n".join("    " + line if line.strip() else "" for line in text.split("\n"))
    with open(init_path, "w", encoding="utf-8") as f:
        f.write(guard + indented)
    GENERATED_FILES.append(f"{SRC_PREFIX}/__init__.py")
    print("  __init__.py patched")

# ── ruff.toml — dynamic per-file-ignores for ALL generated files ──
rt_path = "ruff.toml"
if os.path.exists(rt_path):
    with open(rt_path, encoding="utf-8") as f:
        full = f.read()
    if "Auto-generated by standalone" not in full:
        # Merge bridge-compatible rules into existing ignore list
        BRIDGE_IGNORES = ["E501", "E701", "E702", "ASYNC240", "RUF100", "E902", "T201"]
        full = full.replace(
            "ignore = [",
            "ignore = [\n  " + ", ".join(f'"{r}"' for r in BRIDGE_IGNORES) + ","
        )
        # Append per-file-ignores for ALL generated files
        full += f"\n# Auto-generated by standalone workflow\n[lint.per-file-ignores]\n"
        full += f'"{SRC_PREFIX}/utils/_standalone_fake.py" = ["ALL"]\n'
        for gf in GENERATED_FILES:
            if gf != f"{SRC_PREFIX}/utils/_standalone_fake.py":
                full += f'"{gf}" = ["I001"]\n'
        with open(rt_path, "w", encoding="utf-8") as f:
            f.write(full)
        print(f"  ruff.toml injected ({len(GENERATED_FILES)} files)")
